Add events and requests
ongonets/java-explore-with-me-plus pull request #18
Opened 2024-10-20 19:40 UTC by ongonets

2024-10-23 20:35 UTC, Jim5lives requested changes

2024-10-23 20:35 UTC, Jim5lives commented on main-service/src/main/java/ru/practicum/ewm/errorHandler/ErrorHandler.java
> +    }*/
надо раскомментить

2024-10-23 20:35 UTC, Jim5lives commented on main-service/src/main/java/ru/practicum/ewm/event/controllers/AdminEventController.java
> +public class AdminEventController {
нужна аннотация Validated, иначе аннотация Positive не работает

2024-10-23 20:35 UTC, Jim5lives commented on main-service/src/main/java/ru/practicum/ewm/event/controllers/PrivateEventController.java
> +public class PrivateEventController {
тоже нужна аннотация Validated

2024-10-23 20:35 UTC, Jim5lives commented on main-service/src/main/java/ru/practicum/ewm/event/repository/EventRepository.java
> +import org.springframework.data.querydsl.QuerydslPredicateExecutor;
неиспользуемый импорт

2024-10-23 20:35 UTC, Jim5lives commented on main-service/src/main/java/ru/practicum/ewm/event/service/EventServiceImpl.java
> +        if (categoryId != null) {
Optional я бы проверял через isPresent()

2024-10-23 20:35 UTC, Jim5lives commented on main-service/src/main/java/ru/practicum/ewm/event/service/EventServiceImpl.java
> +                .collect(Collectors.toList());
можно сразу .toList();

2024-10-23 20:35 UTC, Jim5lives commented on main-service/src/main/java/ru/practicum/ewm/request/controller/AdminRequestController.java
> +public class AdminRequestController {
@Validated

2024-10-23 20:35 UTC, Jim5lives commented on main-service/src/main/java/ru/practicum/ewm/request/controller/PrivateRequestController.java
> +public class PrivateRequestController {
@Validated

2024-10-23 20:35 UTC, Jim5lives commented on main-service/src/main/java/ru/practicum/ewm/request/service/RequestServiceImpl.java
> +                                           EventRequestStatusUpdateRequest updateRequest) {
updateRequest - переменная не используется в методе

2024-10-24 04:42 UTC, ongonets commented on main-service/src/main/java/ru/practicum/ewm/errorHandler/ErrorHandler.java
> +    }*/
Там тогда ответы приходят с 500 кодом а не с 400

2024-10-24 04:44 UTC, ongonets commented on main-service/src/main/java/ru/practicum/ewm/event/service/EventServiceImpl.java
> +        if (categoryId != null) {
Тут проверка на наличие самого optional, а не наличия значения в нём

2024-10-24 16:46 UTC, Jim5lives approved these changes

2024-10-24 16:56 UTC, merged